name: LesKitchens CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  WORKSPACE_PATH: /Volumes/workspace/repository
  DERIVED_DATA_PATH: /Volumes/workspace/DerivedData

jobs:
  build:
    name: Build and Test
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Environment
        run: |
          mkdir -p "$WORKSPACE_PATH"
          cp -R . "$WORKSPACE_PATH/"
          
      - name: Run Post-Clone Script
        run: |
          chmod +x "$WORKSPACE_PATH/ci_scripts/ci_post_clone.sh"
          "$WORKSPACE_PATH/ci_scripts/ci_post_clone.sh"
          
      - name: Build
        run: |
          xcodebuild -resolvePackageDependencies \
            -project "$WORKSPACE_PATH/LesKitchens.xcodeproj" \
            -scheme LesKitchens \
            -derivedDataPath "$DERIVED_DATA_PATH"
          
          xcodebuild clean build \
            -project "$WORKSPACE_PATH/LesKitchens.xcodeproj" \
            -scheme LesKitchens \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
            -derivedDataPath "$DERIVED_DATA_PATH" \
            -allowProvisioningUpdates 